### ISSUE TITLE
Ledger Flex Support

### ISSUE THREAD

**Issue by jeaboswell** [helium/wallet-app#872]
**Describe the bug**
Ledger Flex doesn't seem to be supported as an import option.

**To Reproduce**

1. Open the Helium Wallet app for the first time (or go to wherever to add an account)
2. Tap "Pair with Ledger"
3. Choose either Bluetooth or USB Cable, however you wish to connect
4. Ledger Flex is never found

**Expected behavior**
The Leger Flex should be found when pairing with either bluetooth or USB cable.

**Smartphone (please complete the following information):**

- Device: Pixel 7 Pro
- OS: Android 15
- App Version: 2.11.6

**Comment by Codebyethan40** [comment]
@jeaboswell Thanks for getting in touch! If you need any further support, feel free to email us at interact.gitresponse@gmail.com. We're happy to assist!

**Comment by anieto** [comment]
I am also unable to add a Ledger Flex in the wallet app on iOS 18.4 / iPhone 16 Pro. Ledger Nano X works just fine.

**Comment by bryzettler** [comment]
@jeaboswell @anieto Try flex with latest version of app

**Comment by jeaboswell** [comment]
So, it does work on the app now, at least I think so. I am able to connect via bluetooth to the flex, but I can't see the existing solana wallets I have. I got a wallet from the ledger that doesn't match either of the two solana accounts I have already. Any ideas?

**Comment by tomuk5** [comment]
> So, it does work on the app now, at least I think so. I am able to connect via bluetooth to the flex, but I can't see the existing solana wallets I have. I got a wallet from the ledger that doesn't match either of the two solana accounts I have already. Any ideas?

I'm having the exact same issue, the ledger can be pair now but the single account it shows does not match either of the two solana accounts i have already with my helium resources in them.
So it pairs but its no use.

**Comment by jeaboswell** [comment]
So, I guess this may not be the case for the other wallets, but the flex seems to use the full BIP32 standard.  Mine uses "44'/501'/{account}'/{change}'".

See the Brave implementation https://github.com/brave/brave-core/blob/fa5d017c12621b1110c15aa402b0ec7a773a4549/components/brave_wallet_ui/common/hardware/types.ts#L82

I'm not sure if it matters, but the default index value is "x"

**Comment by tomuk5** [comment]
With the announcement of the revesting requirements for august coming out in the past few days, i thought i'd try again.
But still doesnt work, i pair up my ledger to the app and i have a wallet with a pub key that doesnt match any of the wallets on the ledger and the actual wallets that my Helium resources are located in are not shown.

Please can this be fixed rather urgently now, as i can't access any of my helium assets or do anything with them as the helium app cant import the wallets from my ledger. this isnt just a cosmetic issue or minor bug, but is preventing access to helium resources/funds.

**Comment by bryzettler** [comment]
Thanks for bringing this to my attention again, not sure how I missed the notifs. Will be prioritizing a fix for this tomorrow

**Comment by bryzettler** [comment]
Got a pr in review that I hope fixes the issue

**Comment by jeaboswell** [comment]
I saw the pipeline passed for the change on main.  How long does it usually take to push the update out?

**Comment by bryzettler** [comment]
Should have a new release out tomorrow. Need to wait on some reviews

**Comment by bryzettler** [comment]
@jeaboswell @tomuk5 update to `2.14.5` and see if you can import your wallets

**Comment by jeaboswell** [comment]
Okay, so it does show them properly, but when I try to select a single wallet to import, it crashes.  Deselect all works. Deselecting a single wallet fails, and selecting a single wallet after deselecting all fails.

**Comment by bryzettler** [comment]
hmmm, not seeing that on my device. What model phone are you on and is the flex hardwired or over bluetooth?

**Comment by jeaboswell** [comment]
Pixel 7 Pro and bluetooth.  I just added both, and then deleted the one I didn't want.

**Comment by bryzettler** [comment]
sounds like a android specific bug, will try and recreate

**Comment by jeaboswell** [comment]
Also, I hate to add more to this, but I can't seem to connect to the wallet app to the helium builder app or the dashboard at hotspots.hellohelium.com.

**Comment by bryzettler** [comment]
@jeaboswell are there any errors or whats the behavior you're seeing?

**Comment by bryzettler** [comment]
Ah builder app is a completely diff app. Ill have to ping that team, ill look into the online dashboard

**Comment by bryzettler** [comment]
@jeaboswell looks like the QR path with hotspots.hellohelium.com never had logic for singing in with a ledger connected device. Will be adding that but might be a day or two.

**Comment by bryzettler** [comment]
@tomuk5 the `ekKA` wallet is probably the wallet at the 0 index of either root, legacy, default derivation path. It exists on your ledger but you've probably never used it. Do you have a sol balance on the wallet thats not showing up?

**Comment by tomuk5** [comment]
I have a sol balance on the wallet that isnt showing up, i have two wallets with balances:
- Wallet 1, Solana only - i can see this wallet (couldn't see at all before but can now in `2.14.5`)
- Wallet 2, Solana and Helium and IOT - this wallet doesnt show for import (this wallet was created by the helium app at the time of network migration)

**Comment by tomuk5** [comment]
Hi @bryzettler, 

I removed the ledger pairing, updated the app and repaired, but the second wallet still doesnt come through.

I did notice it took a while longer whilst scanning for wallets though.

the base wallet with 0 value is seen at path `m/44'/501'/0'`
my other sol wallet (without helium) is seen at path `m/44'/501'/0'/0'`

the missing wallet is at path `m/44'/501'/1'`

**Comment by bryzettler** [comment]
ah ok, I know the issue. Will work on getting a fix out

**Comment by bryzettler** [comment]
@tomuk5 Check on 2.14.7 if you can get the account at the `m/44'/501'/1'` path now

**Comment by bryzettler** [comment]
@jeaboswell created this https://github.com/helium/wallet-app/issues/958. Not sure when it will get done as we're in the process of phasing out that whole flow and it never supported ledger to begin with.

**Comment by tomuk5** [comment]
Hi @bryzettler sorry for the delay in coming back to you (been on holiday)

this hasn't worked, helium is finding wallets the paths below but still not the wallet at path `m/44'/501'/1'`
```
m/44'/501'
m/44'/501'/0'
m/44'/501'/0'/0'
```

**Comment by bryzettler** [comment]
@tomuk5 all good, I want to say this is now fixed in `2.14.9` so once thats release give it a test and we can close this issue.

**Comment by tomuk5** [comment]
Hi @bryzettler tested in `2.14.11` and this issue is still present, the helium app still wont show or find the wallet at path `m/44'/501'/1'` that it created as part of the solana migration. So im still stuck and can't access my tokens to restake.

**Comment by bryzettler** [comment]
@tomuk5 2.14.15 released

**Comment by tomuk5** [comment]
> [@tomuk5](https://github.com/tomuk5) 2.14.15 should be out soon, sent it for distribution. we also have https://heliumvote.com/ which would have probably worked this whole time with Phantom/Solflare. I completely blanked on mentioning that tho

I can see the wallet when used with Solflare and delegate/undelegate via https://heliumvote.com but still not from the Helium Mobile app.

**Comment by bryzettler** [comment]
@tomuk5 android or ios and the flex is updated to latest firmware?

**Comment by tomuk5** [comment]
Can i use Helumvote.com to move my miners? as they'd be stuck on that account with lots of unclaimed IOT/HNT behind them. If i can't do that via Helumvote then it needs to be fixed.
This is also the wallet at the path that was created by the Helium app at migration to Solana, so just a little bit frustrating if it wont be fixed as its a wallet created by the app in the first place.

**Comment by bryzettler** [comment]
@tomuk5 what is the wallet address that isn't being picked up? If you dont feel comfortable leaving it on here message me on discord `_zyrb` I want to look at the balances associated with it and see why its not getting picked up when my wallet at the same derivation path is.

**Comment by tomuk5** [comment]
I've just moved up to app version 2.14.17 and i can now see the wallet at path `m/44'/501'/1'` and the hotspots within it! 🥳
